import org.bau.Exception
  exception

fun print(x int) throws exception
  if x > 5
    throw exception('Value too large')
  println('x = ' x);

i := 0
while i <= 10
  print(i)
  catch e
    println('Error: ' e.message)
  i += 1

## Expected
x = 0
x = 1
x = 2
x = 3
x = 4
x = 5
Error: Value too large
Error: Value too large
Error: Value too large
Error: Value too large
Error: Value too large
